CLASSNAME:
- cane
- cavallo
- elefante
- farfalla
- gallina
- gatto
- mucca
- pecora
- ragno
- scoiattolo
DATA:
  BATCHSIZES: 16
  DATA_DIR: ../data
  IMG_SIZE:
  - 224
  - 224
  NUM_WORKERS: 4
MODEL:
  CHECKPOINT: '../weights/best.pt'
  EPOCHS: 30
  LEARNING_RATE: 1.0e-05
  LOSS_FUNCTION: CrossEntropyLoss
  MODEL_NAME: resnet50
  NUMCLASS: 10
  OPTIM_FUNCTION: Adam
WEIGHT:
  SAVE_BEST: true
  SAVE_WEIGHT_PATH: ../weights
